pint="/home/a.samir/miniconda3/envs/face/bin/python"

dso1_manip="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-DSO-1-manip.txt"
dso1_auth="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-DSO-1-auth.txt"
cover_manip="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-COVER-manip.txt"
cover_auth="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-COVER-auth.txt"
columbia_manip="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-Columbia-manip.txt"
columbia_auth="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-Columbia-auth.txt"
cocoglide_manip="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-CocoGlide-manip.txt"
cocoglide_auth="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-CocoGlide-auth.txt"
casiav1_manip="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-Casiav1-manip.txt"
casiav1_auth="/scratch/dr/a.samir/IMDL/IMDL-HyFusion/data/IDT-Casiav1-auth.txt"
